name: datacourse
dependencies:
- spacy=0.100.6  # MIT
- dill=0.2.4  # 3-clause BSD
- funcsigs=0.4  # Apache
- py2cairo=1.10.0
- system=5.8
- networkx=1.11  # BSD
- xlrd=0.9.4  # BSD
- html5lib=0.999  # MIT
- sqlparse=0.1.19  # BSD
- partd=0.3.2  # BSD
- fabric=1.10.2  # BSD
- seaborn=0.7.0  # BSD
- flask=0.10.1  # BSD
- ujson=1.35  # BSD
- fastcache=1.0.2  # MIT
- scrapy=1.0.3  # BSD
- pytest=2.9.1  # MIT
- bokeh=0.11.1  # BSD
- sympy=1.0  # 3-clause BSD
- certifi=2015.9.6.2
- flake8=2.5.1  # MIT
- sqlalchemy=1.0.12  # MIT
- quandl=2.8.9  # MIT
- colorama=0.3.7  # BSD
- markdown2=2.3.1  # BSD
- beautiful-soup=4.3.2
- gevent-websocket=0.9.5  # Apache
- boto=2.39.0  # MIT
- pytables=3.2.2  # BSD
- scikit-learn=0.17.1  # 3-clause BSD
- psutil=4.1.0  # BSD
- statsmodels=0.6.1  # 3-clause BSD
- ipython-notebook=4.0.4
- nltk=3.2  # Apache
- chest=0.2.3  # BSD
- pip:
  - amqp==1.4.9  # LGPL
  - anyjson==0.3.3  # BSD
  - audioread==2.1.2  # MIT
  - awscli==1.10.19  # Apache License 2.0
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.4.1  # MIT
  - billiard==3.3.0.23  # BSD
  - botocore==1.4.10  # Apache License 2.0
  - bz2file==0.98  # Apache License, Version 2.0
  - celery==3.1.23  # BSD
  - cython==0.23.1  # License :: OSI Approved :: Apache Software License
  - docker-py==1.8.1  # License :: OSI Approved :: Apache Software License
  - docutils==0.12  # public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)
  - ediblepickle==1.1.3  # Apache 2.0
  - filechunkio==1.6  # MIT license
  - gensim==0.12.4  # LGPL
  - httpretty==0.8.10  # MIT
  - ipython-genutils==0.1.0
  - ipython-sql==0.3.6  # MIT
  - ipywidgets==4.1.1  # BSD
  - jmespath==0.9.0  # License :: OSI Approved :: MIT License
  - joblib==0.9.4  # BSD
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
  - kombu==3.0.35  # License :: OSI Approved :: BSD License
  - librosa==0.4.2  # ISC
  - mock==1.3.0  # License :: OSI Approved :: BSD License
  - mrjob==0.5.0  # Apache
  - oauthlib==1.0.1  # BSD
  - pbr==1.8.1  # License :: OSI Approved :: Apache Software License
  - prettytable==0.7.2
  - py4j==0.9.2  # BSD License
  - pydot2==1.0.33  # MIT
  - pytidylib==0.2.4  # License :: OSI Approved :: MIT License
  - redis==2.10.5  # MIT
  - requests==2.10.0 # Apache 2.0
  - requests-futures==0.9.5  # Apache License v2
  - requests-oauthlib==0.5.0  # ISC
  - responses==0.5.1  # Apache 2.0
  - retrying==1.3.3  # Apache 2.0
  - rsa==3.3  # ASL 2
  - s3transfer==0.0.1  # Apache License 2.0
  - simplejson==3.8.0  # MIT License
  - smart-open==1.3.2
  - tables==3.2.2  # http://www.opensource.org/licenses/bsd-license.php
  - tabulate==0.7.5  # License :: OSI Approved :: MIT License
  - https://github.com/fmfn/UnbalancedDataset/archive/1dc22e22dcd493f6e29e052e27b9f40723eacfe8.zip # MIT
  - us==0.9.1  # BSD
  - websocket-client==0.35.0  # LGPL
